---
- hosts: localhost
  tasks:
    - name: "Install basic Homebrew dependencies"
      homebrew:
        update_homebrew: yes
        state: latest
        name:
          - ansible
          - asdf
          - git
          - gpg2
    - name: "Ensure asdf version manager is loaded by shell"
      lineinfile:
        backup: true
        path: "{{ ansible_env.HOME }}/.zprofile"
        line: "source $(brew --prefix asdf)/asdf.sh"
    - name: "Install Homebrew cask applications"
      homebrew_cask:
        state: present
        update_homebrew: yes
        name:
          - zoomus
          - slack
